### ISSUE TITLE
tmp file error

### ISSUE THREAD

**Issue by MMrhassel** [m4ll0k/CastleBravo#2]
python3 castlebravo.py
[ - ] Running amass...
[ I ] Output: /tmp/8713ce9f428e2**********13.txt
[ E ] ERROR: [Errno 2] No such file or directory: '/tmp/8713ce9f4283***********13.txt'
Traceback (most recent call last):
  File "castlebravo.py", line 399, in <module>
    castleBravoV2().startProcess()
  File "castlebravo.py", line 155, in startProcess
    subdomains = self.subdomainProcess(root)
  File "castlebravo.py", line 226, in subdomainProcess
    t_passive = self.passiveDNS(root) 
  File "castlebravo.py", line 306, in passiveDNS
    os.remove(randomTmpPath+ext)

**Comment by m4ll0k** [comment]
your os?

**Comment by MMrhassel** [comment]
Ubuntu

**Comment by m4ll0k** [comment]
@MMrhassel  is very strange! because it goes to create a temporary file ` /tmp/8713ce9f428e2**********13.txt`, once processed the file goes to remove it to save space! try to delete all the files in /tmp before launching it! is tell me what happens!
